spring:
  application:
    name: auth-service
server:
  port: 8094

app:
  keycloak:
    client:
      id: springsecurity
      secret: ${KEYCLOAK_CLIENT_SECRET:egD63JWeQQLVP7OY8P2qAPR5eIwvR5Zp}
    realm: taxi
    server-url: http://localhost:8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost