spring:
  application:
    name: auth-service
server:
  port: 8081

app:
  keycloak:
    jwk-url: http://localhost:8080/realms/taxi/protocol/openid-connect/certs
    admin:
      username: admin
      password: admin
    client:
      id: springsecurity
      secret: S2MBpMpOceFatgFrWFRgAqHot49WcDCy
    realm: taxi
    server-url: http://localhost:8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
