spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: passenger-service-route
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers/**
        - id: driver-service-route
          uri: lb://driver-service
          predicates:
            - Path=/api/v1/drivers/**
        - id: driver-service-cars-route
          uri: lb://driver-service
          predicates:
            - Path=/api/v1/cars/**
        - id: ride-service-route
          uri: lb://ride-service
          predicates:
            - Path=/api/v1/rides/**
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/taxi/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8642