spring:
  application:
    name: promocode-service

  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017}/promocode_db
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8095