spring:
  application:
    name: promocode-service

  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017}/promocode_db
      auto-index-creation: true

  kafka:
    bootstrap-servers: localhost:29092
    schema-registry:
      url: http://localhost:8081
    groups:
      promocode-usage: promocode-usage-group
    topics:
      promocode-usage: promocode-usage-topic
    consumers-number: 3
    error-handler:
      backoff:
        min-interval: 1000
        max-interval: 10000
        multiplier: 2.0

springdoc:
  api-docs:
    path: /api/v1/promocodes/docs/v3/api-docs
  swagger-ui:
    path: /api/v1/promocodes/docs/swagger-ui.html

management:
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8095