spring:
  application:
    name: ride-service

  datasource:
    url: ${PG_URL}/ride_service_db
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:29092
    schema-registry:
      url: http://localhost:8081
    partition-number: 3
    replicas-number: 1
    topics:
      rate-passenger: rate-passenger-topic
      rate-driver: rate-driver-topic

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/taxi/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      hostname: localhost

server:
  port: 8093
