spring:
  application:
    name: ride-service

  datasource:
    url: ${PG_URL}/ride_service_db
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:29092
    schema-registry:
      url: http://localhost:8081
    partition-number: 3
    replicas-number: 1
    topics:
      rate-passenger: rate-passenger-topic
      rate-driver: rate-driver-topic
      promocode-usage: promocode-usage-topic
      ride-payment: ride-payment-topic

management:
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

client:
  passenger-service:
    name: passenger-service
    path: api/v1/passengers
  driver-service:
    name: driver-service
    path: api/v1/drivers
  payment-service:
    name: payment-service
    path: api/v1/payments
  promocode-service:
    name: promocode-service
    path: api/v1/promocodes

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        minimum-number-of-calls: 5
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - feign.RetryableException

springdoc:
  api-docs:
    path: /api/v1/rides/docs/v3/api-docs
  swagger-ui:
    path: /api/v1/rides/docs/swagger-ui.html

server:
  port: 8093
